[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true npm ci --omit=dev"]

[phases.build]
cmds = ["echo 'No build step required'"]

[start]
cmd = "node src/server.js"
