[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm config set fund false",
  "npm config set audit false", 
  "export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true",
  "npm ci --omit=dev --omit=optional --silent"
]

[phases.build]
cmds = ["echo 'Build optimized for Railway deployment'"]

[start]
cmd = "node src/server.js"

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
NODE_ENV = "production"
